# Data Preparation: Part 2 - location_id

## 1. Import Packages

In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
pip install pycountry

Requirement already satisfied: pycountry in /opt/conda/lib/python3.12/site-packages (26.2.16)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pycountry

## 2. Import Raw Data

In [4]:
df = pd.read_csv('/home/jovyan/MSBA Mod 5/Final Deliverable/Data Cleaning and Feature Engineering/Raw Input Files/asrs_full.csv')

## 3. Clean Data

### 3.1. Split Data & Assign Airport/Location Details

In [5]:
df[['airport', 'organizational_unit']] = df['location_id'].str.split('.', n=1, expand=True)

In [6]:
# Change variations of "ZZZ" (censored data) to "ZZZ"

replace = ['ZZZ1', 'ZZZ2', 'ZZZ3', 'ZZZZ', 'ZZZZ1', 'ZZZZ2', 'ZZZZZ']
for x in replace:
    df.loc[df['airport'] == x, 'airport'] = "ZZZ"
    # data_enc.loc[data_enc['PrimaryProblem'] == "Ambiguous", 'PrimaryProblem'] = "OTHER"

In [7]:
df

,acn,event_date,anomaly_code,location_id,aircraft_type,reporter_function,flight_phase,narrative_text,synopsis,word_count,...,causal_connective_count,specificity_score,named_entity_count,type_token_ratio,recurrence_flag,days_to_recurrence,is_right_censored,label_method,airport,organizational_unit
0,1507557,2018-01-01,ATC Issue All Types; Deviation / Discrepancy -...,C90.TRACON,A330,Approach,Landing,Aircraft X was assigned a runway approximately...,MLI Approach Controller reported ATC denied th...,143,...,2,0.00,7,0.5833,1,181.0,0,exact_anomaly_code_same_location_12mo,C90,TRACON
1,1513720,2018-01-01,Aircraft Equipment Problem Less Severe,ZZZ.Airport,EMB ERJ 170/175 ER/LR,Captain; Pilot Not Flying,Cruise,Pack 2 was MELed. My FO (First Officer) and I ...,ERJ-175 Captain reported diverting after exper...,318,...,3,0.75,19,0.4969,0,NaN,0,exact_anomaly_code_same_location_12mo,ZZZ,Airport
2,1513718,2018-01-01,Flight Deck / Cabin / Aircraft Event Illness /...,ZZZ.ARTCC,A321,Pilot Not Flying,Cruise,[A passenger] was reported as being ill and un...,A321 flight crew member reported difficulty re...,166,...,0,0.00,13,0.5689,1,120.0,0,exact_anomaly_code_same_location_12mo,ZZZ,ARTCC
3,1513706,2018-01-01,Aircraft Equipment Problem Critical,ZZZ.Airport,Citation V/Ultra/Encore (C560),First Officer; Pilot Flying,Final Approach,While on approach at 1;500ft; we asked the tow...,CE-560 First Officer reported that while on ap...,268,...,1,0.50,11,0.5221,0,NaN,0,exact_anomaly_code_same_location_12mo,ZZZ,Airport
4,1513663,2018-01-01,Aircraft Equipment Problem Less Severe; Deviat...,RCTP.Airport,B747-400,Pilot Flying; Captain,NaN,Our aircraft had just finished a 'heavy' maint...,B747-400 Captain reported a loss of hydraulic ...,190,...,0,0.25,5,0.5812,0,NaN,0,exact_anomaly_code_same_location_12mo,RCTP,Airport
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33718,2192919,2024-12-01,Aircraft Equipment Problem Critical; Deviation...,ZZZ.Airport,Skyhawk 172/Cutlass 172,Instructor,Climb,This occurred shortly after departing from ZZZ...,C172 Flight Instructor reported cockpit smoke ...,258,...,0,0.25,19,0.6151,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport
33719,2192908,2024-12-01,Deviation - Altitude Overshoot; Deviation / Di...,CRQ.Airport,Any Unknown or Unlisted Aircraft Manufacturer,Single Pilot; Pilot Flying,Final Approach,I departed from ZZZ with a filed IFR flight pl...,GA pilot reported they descended below the Min...,579,...,4,0.50,33,0.4220,0,NaN,1,exact_anomaly_code_same_location_12mo,CRQ,Airport
33720,2192884,2024-12-01,Conflict NMAC; Deviation / Discrepancy - Proce...,ZZZ.Airport,Skyhawk 172/Cutlass 172,Instructor,Final Approach,Practice approach RNAV XX into ZZZ. I am the C...,C172 flight instructor reported a near mid-air...,63,...,0,0.25,8,0.7969,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport
33721,2192873,2024-12-01,Deviation / Discrepancy - Procedural Published...,ZZZ.Airport,A319,Ramp,Taxi,My shift started at XA:00 AM and I was assigne...,Tow team lead reported after parking aircraft ...,1930,...,5,0.75,49,0.2664,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport
33722,2253308,2024-12-01,Conflict NMAC,HII.Airport,Light Transport; Low Wing; 2 Turboprop Eng,NaN,NaN,Aircraft X and Aircraft Y nearly collide over ...,Reporter reported a near mid air collision bet...,30,...,0,0.00,3,0.9355,0,NaN,1,exact_anomaly_code_same_location_12mo,HII,Airport

In [8]:
# df.to_csv("Intermediate Input Files/locationsplit.csv", index=False)

In [9]:
unique_airport = df['airport'].unique()
print(unique_airport)

['C90' 'ZZZ' 'RCTP' ... 'N94' 'JAQ' 'CVC']

In [10]:
with pd.option_context('display.max_rows', None):
    display(df['airport'].value_counts())

airport
ZZZ      22574
DEN        273
ORD        248
EWR        232
LAX        194
SFO        176
SCT        170
CLT        160
IAH        143
DFW        141
LGA        135
MIA        118
DCA        117
ATL        114
D01        114
ZAB        113
ZDV        102
PHL        100
ZJX         98
NCT         97
ZDC         94
SEA         93
ZLC         90
PHX         90
N90         89
BOS         89
LAS         88
ZLA         87
JFK         84
PCT         75
ZMA         72
ZOA         71
ZSE         67
ROA         66
ZNY         64
SJC         64
SAN         60
MDW         59
IAD         58
SNA         58
ZAU         58
ZOB         57
MCO         57
ZBW         57
BNA         57
SAT         55
BOI         55
ZHU         54
BWI         53
ZTL         50
C90         49
TEB         49
ZFW         48
I90         47
DTW         47
SLC         45
VNY         45
ZMP         45
BUR         44
S46         44
ABQ         43
MEM         43
RNO         43
ASE         42
P50         42
ZKC         42
OAK         42
ZID         42
FLL         38
TPA         38
ELP         36
ZME         36
MSP         36
D10         36
BFI         35
AUS         35
HCF         34
DAL         34
PDX         34
HOU         34
SDF         33
IND         32
S56         32
HNL         32
A90         32
PIT         32
BJC         32
L30         31
CVG         30
ONT         30
MMFR        28
A80         28
BHM         26
AVL         25
EUG         25
HPN         25
ZAN         25
PBI         25
STL         24
A11         24
HECC        24
GEG         23
LGB         23
PAO         23
CLE         23
ANC         23
F11         23
RSW         22
APA         22
RDU         22
TUS         22
MYF         21
MRY         21
SBA         21
PDK         21
CMH         21
SYR         21
SQL         20
COS         20
FAI         20
MCI         20
MSY         20
FXE         19
SMF         19
AUO         19
KZAK        19
MMMX        18
LTAA        18
JAX         18
IWA         18
RIC         17
MKE         17
CHO         17
UNV         17
PAE         16
SMO         16
MFR         16
PWM         16
ORF         16
DAB         16
AFW         16
SDL         15
ORL         15
MDT         15
GSO         15
PSP         15
SAV         15
CAE         14
BED         14
SRQ         14
ALB         14
JYO         14
OGG         14
OKC         14
LLLL        14
CHS         14
BUF         14
SBN         14
LMO         14
P80         14
FNL         13
CZQX        13
MMUN        13
MMU         13
LLBG        13
DSM         13
CHA         13
BGR         13
CRW         13
PVD         13
D21         13
MSO         13
LFPG        12
LAL         12
VHHH        12
TYS         12
LVK         12
FCM         12
CYYZ        12
HTS         11
VNC         11
SGU         11
CAK         11
EGGX        11
OSH         11
MSN         11
F70         11
EGLL        11
SUS         11
DWH         11
GSP         11
BZN         11
MYR         11
JAC         11
BTV         11
GRR         11
DVT         11
EGE         11
OMA         10
AVQ         10
AVP         10
CNO         10
HWD         10
ROC         10
RFD         10
RDM         10
SKBO        10
LIT         10
M98         10
RKSI         9
MGGT         9
MKJS         9
HIO          9
RJJJ         9
CID          9
LCCC         9
ISP          9
ICT          9
SBP          9
FFZ          9
SBGR         9
GIF          9
BDL          9
MMGL         9
CGZ          9
PTKK         9
MYNN         9
RKRR         9
ISM          9
MHT          8
FRG          8
CPT          8
RNT          8
ILM          8
GYR          8
ADS          8
BFL          8
GTF          8
MLB          8
PRC          8
HEF          8
OPF          8
GFK          8
FAT          8
MOB          8
HND          8
STS          8
FDK          8
PWT          7
RNM          7
TRI          7
CRG          7
APC          7
DED          7
FTW          7
DAY          7
TVC          7
CMA          7
DPA          7
RHV          7
JNU          7
TUL          7
BTR          7
ZSHA         7
JWN          7
AMA          7
FPR          7
CHD          7
MROC         7
GJT          7
OPLR         7
MSLP         7
PHF          7
SSI          7
SUX          6
U90          6
SAC          6
TOA          6
R90          6
HDN          6
TRM          6
OEJD         6
MKC          6
TTN          6
LZU          6
X04          6
GAI          6
JAN          6
OMN          6
WSSS         6
CPS          6
PIE          6
P08          6
C83          6
MPTO         6
ITH          6
CKB          6
JVY          6
TJSJ         6
SFB          6
PNE          6
WHP          6
TRK          6
BDN          6
VGT          6
AWO          6
JCF          6
ZBPE         6
GMU          6
ITO          6
APF          6
GPT          6
SJU          6
EDDF         6
PGV          6
FSD          6
KTN          5
MGM          5
TTD          5
MWH          5
JNX          5
DXR          5
MRI          5
ELM          5
ACT          5
VIDF         5
POU          5
LRU          5
LAN          5
GRK          5
ABE          5
LNK          5
MMSD         5
CDW          5
LUK          5
BIL          5
BDR          5
SEE          5
ESN          5
BET          5
HII          5
ZSPD         5
BMI          5
CXP          5
BTL          5
ZHN          5
MLU          5
PVU          5
GXY          5
LSE          5
HLN          5
WVI          5
E63          5
CYVR         5
MRLB         5
HQZ          5
OJAC         5
FFC          5
MLI          5
TMB          5
PKMJ         4
SAF          4
HHR          4
TIX          4
ZWY          4
TLH          4
RDG          4
ZGZU         4
RAL          4
PUB          4
RCTP         4
SPI          4
HUF          4
UHMM         4
HYI          4
OGD          4
CZYZ         4
CZUL         4
ECP          4
SJT          4
LEX          4
EZF          4
UES          4
VHHK         4
MDSD         4
MAF          4
ZSU          4
MLE          4
LAF          4
U42          4
RVS          4
NFFF         4
FLY          4
PWK          4
MCC          4
OSU          4
BCV          4
SOP          4
RJAA         4
BTF          4
HWO          4
RIL          4
GVL          4
BIRD         4
ERI          4
PLU          4
RJTT         4
BIF          4
SUU          4
GUM          4
BGM          4
DYB          4
KOA          4
RAP          4
TSP          4
EVV          4
VVNB         4
CCR          4
RIV          4
MYAM         4
OAJ          4
HSV          4
SBCW         4
Y90          4
SMQ          4
TCY          4
CCB          4
SFF          4
UUWV         4
MMPR         4
XNA          4
SCK          4
MHLM         4
EIDW         4
FTY          4
ILG          4
COE          4
UAO          4
NEW          4
DET          4
SKED         4
ARR          4
CDC          4
VRB          4
UAAA         3
NUQ          3
LRD          3
ORBB         3
LEE          3
CXY          3
RYY          3
DMW          3
MVY          3
PGSN         3
CXO          3
MKT          3
NYL          3
VLD          3
UGN          3
2R2          3
SEFG         3
LOU          3
FLG          3
VPZ          3
PIA          3
JVL          3
CPR          3
FCI          3
REI          3
WRI          3
EDGG         3
BKV          3
46U          3
DIK          3
YSSY         3
GON          3
VPC          3
LHCC         3
EVB          3
MMV          3
ZUA          3
SGH          3
TNCA         3
ZBAA         3
SSF          3
FOK          3
HRL          3
ASD          3
LIH          3
VUO          3
UUU          3
LCH          3
MBPV         3
PAMR         3
VBT          3
BOW          3
GEU          3
LRBB         3
VIS          3
DIA          3
CYUL         3
VKX          3
MHRO         3
FAY          3
MTJ          3
NTD          3
7FL6         3
LBB          3
MQY          3
LVJ          3
BLM          3
N40          3
HXD          3
SBD          3
OJAI         3
LXT          3
47N          3
IKV          3
MUHA         3
SPIM         3
TJZS         3
S43          3
SPG          3
HDC          3
VPS          3
DLH          3
MHK          3
T75          3
LOT          3
3J1          3
OWD          3
TPF          3
AGC          3
S50          3
L18          3
BDU          3
MEV          3
LPPT         3
DRO          3
LYH          3
LTBB         3
MUFH         3
EISN         3
AZO          3
ALW          3
BFF          3
BLI          3
BAZ          3
GRB          3
CRP          3
OOMM         3
E10          3
JZP          3
CRQ          3
ZGSZ         3
GPI          3
SHV          3
AGS          3
BXK          3
EGTT         3
IWS          3
VABB         3
MHTG         3
RST          3
TKPK         3
CLL          3
TVY          2
EGPX         2
FSM          2
EKM          2
F45          2
MTN          2
EDUU         2
GYH          2
DKX          2
FFT          2
06A          2
GZH          2
SBGL         2
PCW          2
JBR          2
HCR          2
PUW          2
MDH          2
0W3          2
MHR          2
SFM          2
ASH          2
CYEG         2
PVC          2
BRD          2
SBM          2
BVY          2
BWG          2
PNS          2
CFO          2
I19          2
OUN          2
LHD          2
AUN          2
BHB          2
1W1          2
CZQM         2
EMT          2
CSG          2
GGW          2
AEG          2
MMQT         2
MTPP         2
33N          2
GYY          2
LNC          2
4I3          2
VCB          2
BYY          2
JQF          2
JZI          2
VABF         2
ACY          2
JRF          2
CEW          2
EDU          2
IAG          2
BCT          2
FNT          2
FAR          2
SLI          2
S95          2
1K1          2
SWO          2
IOW          2
TWF          2
LUF          2
FWA          2
MMCU         2
PAQ          2
OKV          2
TKI          2
JLN          2
CBF          2
CPK          2
MKO          2
CMI          2
7B3          2
7F3          2
SYCJ         2
OBE          2
AND          2
PMV          2
IDA          2
RTS          2
1R8          2
F82          2
EHAA         2
VYYF         2
HMP          2
ACK          2
LHW          2
CYMX         2
3DW          2
TIW          2
LIEO         2
X26          2
O88          2
ADQ          2
MMH          2
EAT          2
PSM          2
AVX          2
O69          2
BRO          2
GLS          2
GTU          2
TJIG         2
NUW          2
FHR          2
PYM          2
ABI          2
AJO          2
O61          2
39N          2
LCI          2
DVL          2
RCZ          2
TVL          2
YKM          2
YIP          2
X59          2
DSV          2
4B6          2
FIN          2
GYI          2
ABR          2
T31          2
CGI          2
I69          2
OMDB         2
ARB          2
SZP          2
MDPC         2
PTK          2
MDPP         2
GFL          2
MIC          2
EYE          2
EQY          2
HWV          2
EDC          2
LOM          2
MWO          2
BIH          2
GA2          2
COI          2
MVN          2
VDF          2
RAC          2
TNCM         2
M54          2
SUN          2
HUM          2
MMLO         2
DLZ          2
LEBL         2
OWA          2
LIMM         2
SPS          2
CGF          2
CZEG         2
SMD          2
CYYC         2
CVB          2
ILN          2
SUZ          2
AAO          2
OKK          2
PMP          2
SUA          2
BAF          2
7S3          2
LBE          2
TCL          2
VQQ          2
GPM          2
LNS          2
DKB          2
VCV          2
LUD          2
CWA          2
TIST         2
MFE          2
MOT          2
EDDM         2
MKL          2
HFY          2
FIT          2
PWA          2
DNL          2
MGJ          2
CVH          2
XNX          2
RYM          2
RCAA         2
SGF          2
OXR          2
RPHI         2
MKY          2
LWC          2
1F7          2
BVU          2
BKL          2
FCA          2
ORS          2
GNV          2
SPB          2
ELA          2
JPX          2
SLE          2
PUJ          2
HKS          2
LMT          2
VLL          2
ENN          2
RDD          2
RJBB         2
SEZ          2
DBQ          2
DIJ          2
TOL          2
GUC          2
CEU          2
BIS          2
PCZ          2
44N          2
MDD          2
BTP          2
CVC          1
MEZ          1
IXA          1
I43          1
DEC          1
IXD          1
60R          1
OBI          1
ONZ          1
GPH          1
HYA          1
ALM          1
ISO          1
IPT          1
80G          1
MTW          1
CWC          1
UUWW         1
8W2          1
WLD          1
AWG          1
OZW          1
MKG          1
EAU          1
HSD          1
TDF          1
LIC          1
MYEF         1
LECM         1
TPL          1
INF          1
LGC          1
CLW          1
GKY          1
CVS          1
W13          1
LBSR         1
CVN          1
MSV          1
IRK          1
M91          1
ANI          1
AXH          1
83D          1
PVB          1
NGU          1
7G8          1
OAR          1
PIH          1
W35          1
MRC          1
PVW          1
EEO          1
X60          1
VER          1
JHW          1
PJY          1
OCH          1
LDJ          1
U10          1
FWN          1
SFZ          1
LFPB         1
LWA          1
RBV          1
ODO          1
CCO          1
T35          1
LRO          1
PVR          1
LOWW         1
CYS          1
CDN          1
MTO          1
50R          1
ANP          1
SSQ          1
MWC          1
7S1          1
WYS          1
BIKF         1
THA          1
4M3          1
ORK          1
LCLK         1
RNH          1
EUL          1
COU          1
CGS          1
1N7          1
T67          1
DTS          1
PKB          1
PHLI         1
AUH          1
ATW          1
L35          1
3AU          1
STP          1
AMG          1
20GA         1
MUSC         1
MKJK         1
MWCR         1
MMSP         1
SWF          1
NZZO         1
CZVR         1
LNY          1
HUA          1
UNU          1
FUL          1
OMDW         1
PXR          1
3B3          1
ADF          1
MEB          1
15MO         1
GVQ          1
FA44         1
GVT          1
06C          1
SNH          1
TYQ          1
RWI          1
FHU          1
W29          1
F51          1
BVS          1
M03          1
SAA          1
VVTS         1
AJZ          1
MOD          1
BCB          1
AWM          1
SMN          1
JSD          1
S36          1
GUTER        1
PSC          1
EDDK         1
SAEF         1
P19          1
TGI          1
EYW          1
PRX          1
SEF          1
FVX          1
18AZ         1
LNN          1
HLX          1
Y23          1
HJH          1
RYN          1
OXC          1
SVZM         1
HDF          1
MYL          1
HLM          1
WI14         1
UIM          1
C02          1
GAF          1
OQU          1
DNN          1
MIO          1
SGJ          1
F05          1
M38          1
IUA          1
ONL          1
SIF          1
ZSWX         1
AFO          1
RPLC         1
TTA          1
TEX          1
MYGF         1
LXV          1
PHKO         1
MGY          1
FYJ          1
9PA8         1
2V6          1
CO15         1
SUT          1
MMMZ         1
RBG          1
LAW          1
1G3          1
3B1          1
CIU          1
ICL          1
SET          1
A39          1
UIN          1
POF          1
IYK          1
X52          1
ZZV          1
C44          1
46N          1
NFW          1
GCY          1
SAEZ         1
1TE4         1
PIL          1
MHV          1
SDY          1
RUT          1
EBBU         1
BQN          1
MZBZ         1
33V          1
L52          1
5I4          1
LFFF         1
CYTZ         1
ROG          1
MNZ          1
PRB          1
2WA1         1
TS36         1
LNP          1
EHF          1
06N          1
OAKX         1
DUY          1
HYR          1
OKB          1
RCM          1
N85          1
MPR          1
52F          1
IGM          1
LGU          1
YBBB         1
OBBS         1
U08          1
ACJ          1
SPF          1
SEQM         1
2R4          1
CEC          1
MYEM         1
X51          1
CTY          1
UT25         1
RYW          1
CPM          1
D50          1
S05          1
INK          1
EKO          1
BKT          1
HDO          1
7A8          1
IMT          1
RBD          1
PEO          1
MIE          1
GLL          1
1C9          1
FUELR        1
MMEX         1
23M          1
MBS          1
MMTJ         1
MRN          1
TME          1
MDST         1
SHD          1
CQA          1
0OR9         1
COL          1
48D          1
IYS          1
C81          1
HMN          1
ULMM         1
LKR          1
FWB          1
OSC          1
EDF          1
EBZW         1
YRK          1
JWG          1
BQ1          1
CVO          1
AMR          1
CNW          1
PKWA         1
JHM          1
MMTC         1
UOX          1
MJX          1
UDD          1
SLN          1
DWG          1
BFM          1
MUVR         1
TKC          1
CLS          1
E68          1
ALS          1
CYXX         1
MNV          1
FCH          1
PVG          1
IMS          1
GGG          1
ALO          1
OCF          1
TVF          1
OCN          1
LAR          1
M41          1
ZGHA         1
S72          1
MRF          1
OQN          1
TYR          1
MRJ          1
LFT          1
OLM          1
7S5          1
11R          1
SZT          1
061          1
INL          1
IEN          1
GQO          1
HVR          1
LECB         1
LWM          1
TWM          1
VTI          1
STK          1
BKX          1
HEG          1
SRB          1
L62          1
CUVOT        1
EMV          1
ADW          1
6R3          1
TAD          1
MXO          1
C91          1
RBM          1
MCF          1
MMLP         1
3KY4         1
P31          1
DXE          1
1Z1          1
BVI          1
N47          1
OTBH         1
DE25         1
GCN          1
HTO          1
9V9          1
W03          1
DLG          1
HSP          1
HOM          1
FA83         1
SVMC         1
Y50          1
AXN          1
09J          1
1I9          1
TBPB         1
BEH          1
KWA          1
MEI          1
AKR          1
OME          1
MPMG         1
SWI          1
DVV          1
UBBA         1
BIV          1
I68          1
5C1          1
THV          1
C65          1
PSO          1
LIPZ         1
OMBON        1
Z09          1
CKZ          1
LKU          1
0L7          1
JKA          1
RKD          1
LOZ          1
SLIDR        1
IRS          1
MMES         1
MBO          1
RMN          1
8A3          1
SPA          1
I73          1
IKK          1
EBD          1
BTY          1
54J          1
P20          1
AXX          1
BMC          1
Y49          1
DWA          1
EFK          1
OJC          1
CKN          1
C25          1
09IA         1
SYJC         1
FOE          1
DYL          1
4V4          1
ONP          1
RJTG         1
2W5          1
MMTO         1
ORD2         1
AOH          1
BFD          1
SEM          1
MYBC         1
AHN          1
STJ          1
HRJ          1
WJF          1
FMN          1
ATA          1
SDM          1
TRL          1
YNG          1
DNMM         1
IZA          1
RCA          1
C29          1
DOV          1
TXK          1
OKBK         1
EHAM         1
GOK          1
JFX          1
FAJS         1
48TX         1
MDCS         1
TX94         1
10C          1
ERV          1
ZWUQ         1
AIZ          1
1V6          1
NRT          1
ELN          1
X14          1
EDJ          1
PXT          1
CQX          1
STC          1
NFL          1
IPJ          1
RCSS         1
2W3          1
UMP          1
IGQ          1
VUH          1
LPPR         1
PAN          1
LIRN         1
AMW          1
4CO2         1
K81          1
D56          1
LYBA         1
PTYA         1
SEP          1
U69          1
VVS          1
TOI          1
AST          1
DRP          1
LTFE         1
2R1          1
LUA          1
OLV          1
OMAE         1
X65          1
SHN          1
MBT          1
HDH          1
MPO          1
LVM          1
SCH          1
ZYSH         1
VOBL         1
ACINS        1
CWF          1
E25          1
UAM          1
BFR          1
LUG          1
JRA          1
VDI          1
CMD          1
YMMM         1
0C8          1
PBG          1
SHR          1
CZK          1
SLR          1
BTT          1
4S2          1
6B0          1
DHN          1
C35          1
ZSSS         1
SNS          1
COF          1
BGQ          1
31E          1
SKX          1
S37          1
LVN          1
MMSM         1
NLC          1
ACV          1
1H0          1

In [11]:
# Load your data
df = pd.read_csv('Intermediate Input Files/locationsplit.csv')

# Load OurAirports data
airports = pd.read_csv('Raw Input Files/airports.csv')

# Add municipality to the lookup
lookup = airports[['ident', 'iata_code', 'iso_country', 'iso_region', 'municipality']].copy()

# Build mapping dicts
icao_map = lookup.set_index('ident')[['iso_country', 'iso_region', 'municipality']].to_dict('index')
iata_map = lookup.dropna(subset=['iata_code']).set_index('iata_code')[['iso_country', 'iso_region', 'municipality']].to_dict('index')

In [12]:
def get_country_name(iso_code):
    try:
        return pycountry.countries.get(alpha_2=iso_code).name
    except:
        return iso_code  # fall back to ISO code if not found

def get_location(code):
    if pd.isna(code):
        return None, None, None
    match = icao_map.get(code) or iata_map.get(code)
    if not match:
        return None, None, None
    country = match['iso_country']
    region = match['iso_region']
    city = match['municipality']
    if country == 'US':
        return 'United States', region.split('-')[-1], city
    return get_country_name(country), None, city

df[['country', 'state', 'city']] = df['airport'].apply(
    lambda x: pd.Series(get_location(x))
)

In [13]:
df

,acn,event_date,anomaly_code,location_id,aircraft_type,reporter_function,flight_phase,narrative_text,synopsis,word_count,...,type_token_ratio,recurrence_flag,days_to_recurrence,is_right_censored,label_method,airport,organizational_unit,country,state,city
0,1507557,2018-01-01,ATC Issue All Types; Deviation / Discrepancy -...,C90.TRACON,A330,Approach,Landing,Aircraft X was assigned a runway approximately...,MLI Approach Controller reported ATC denied th...,143,...,0.5833,1,181.0,0,exact_anomaly_code_same_location_12mo,C90,TRACON,None,None,None
1,1513720,2018-01-01,Aircraft Equipment Problem Less Severe,ZZZ.Airport,EMB ERJ 170/175 ER/LR,Captain; Pilot Not Flying,Cruise,Pack 2 was MELed. My FO (First Officer) and I ...,ERJ-175 Captain reported diverting after exper...,318,...,0.4969,0,NaN,0,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None
2,1513718,2018-01-01,Flight Deck / Cabin / Aircraft Event Illness /...,ZZZ.ARTCC,A321,Pilot Not Flying,Cruise,[A passenger] was reported as being ill and un...,A321 flight crew member reported difficulty re...,166,...,0.5689,1,120.0,0,exact_anomaly_code_same_location_12mo,ZZZ,ARTCC,None,None,None
3,1513706,2018-01-01,Aircraft Equipment Problem Critical,ZZZ.Airport,Citation V/Ultra/Encore (C560),First Officer; Pilot Flying,Final Approach,While on approach at 1;500ft; we asked the tow...,CE-560 First Officer reported that while on ap...,268,...,0.5221,0,NaN,0,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None
4,1513663,2018-01-01,Aircraft Equipment Problem Less Severe; Deviat...,RCTP.Airport,B747-400,Pilot Flying; Captain,NaN,Our aircraft had just finished a 'heavy' maint...,B747-400 Captain reported a loss of hydraulic ...,190,...,0.5812,0,NaN,0,exact_anomaly_code_same_location_12mo,RCTP,Airport,"Taiwan, Province of China",None,Taoyuan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33718,2192919,2024-12-01,Aircraft Equipment Problem Critical; Deviation...,ZZZ.Airport,Skyhawk 172/Cutlass 172,Instructor,Climb,This occurred shortly after departing from ZZZ...,C172 Flight Instructor reported cockpit smoke ...,258,...,0.6151,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None
33719,2192908,2024-12-01,Deviation - Altitude Overshoot; Deviation / Di...,CRQ.Airport,Any Unknown or Unlisted Aircraft Manufacturer,Single Pilot; Pilot Flying,Final Approach,I departed from ZZZ with a filed IFR flight pl...,GA pilot reported they descended below the Min...,579,...,0.4220,0,NaN,1,exact_anomaly_code_same_location_12mo,CRQ,Airport,Brazil,None,Caravelas
33720,2192884,2024-12-01,Conflict NMAC; Deviation / Discrepancy - Proce...,ZZZ.Airport,Skyhawk 172/Cutlass 172,Instructor,Final Approach,Practice approach RNAV XX into ZZZ. I am the C...,C172 flight instructor reported a near mid-air...,63,...,0.7969,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None
33721,2192873,2024-12-01,Deviation / Discrepancy - Procedural Published...,ZZZ.Airport,A319,Ramp,Taxi,My shift started at XA:00 AM and I was assigne...,Tow team lead reported after parking aircraft ...,1930,...,0.2664,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None
33722,2253308,2024-12-01,Conflict NMAC,HII.Airport,Light Transport; Low Wing; 2 Turboprop Eng,NaN,NaN,Aircraft X and Aircraft Y nearly collide over ...,Reporter reported a near mid air collision bet...,30,...,0.9355,0,NaN,1,exact_anomaly_code_same_location_12mo,HII,Airport,United States,AZ,Lake Havasu City

In [14]:
# df.to_csv('Intermediate Input Files/LocationID.csv', index=False)

In [15]:
# Build mapping dicts for type only
icao_map = airports.set_index('ident')['type'].to_dict()
iata_map = airports.dropna(subset=['iata_code']).set_index('iata_code')['type'].to_dict()

# Map airport type
df['airport_type'] = df['airport'].apply(
    lambda x: icao_map.get(x) or iata_map.get(x) if pd.notna(x) else None
)

# Overwrite the existing file
# df.to_csv('Intermediate Input Files/LocationID.csv', index=False)

In [16]:
df

,acn,event_date,anomaly_code,location_id,aircraft_type,reporter_function,flight_phase,narrative_text,synopsis,word_count,...,recurrence_flag,days_to_recurrence,is_right_censored,label_method,airport,organizational_unit,country,state,city,airport_type
0,1507557,2018-01-01,ATC Issue All Types; Deviation / Discrepancy -...,C90.TRACON,A330,Approach,Landing,Aircraft X was assigned a runway approximately...,MLI Approach Controller reported ATC denied th...,143,...,1,181.0,0,exact_anomaly_code_same_location_12mo,C90,TRACON,None,None,None,None
1,1513720,2018-01-01,Aircraft Equipment Problem Less Severe,ZZZ.Airport,EMB ERJ 170/175 ER/LR,Captain; Pilot Not Flying,Cruise,Pack 2 was MELed. My FO (First Officer) and I ...,ERJ-175 Captain reported diverting after exper...,318,...,0,NaN,0,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None,None
2,1513718,2018-01-01,Flight Deck / Cabin / Aircraft Event Illness /...,ZZZ.ARTCC,A321,Pilot Not Flying,Cruise,[A passenger] was reported as being ill and un...,A321 flight crew member reported difficulty re...,166,...,1,120.0,0,exact_anomaly_code_same_location_12mo,ZZZ,ARTCC,None,None,None,None
3,1513706,2018-01-01,Aircraft Equipment Problem Critical,ZZZ.Airport,Citation V/Ultra/Encore (C560),First Officer; Pilot Flying,Final Approach,While on approach at 1;500ft; we asked the tow...,CE-560 First Officer reported that while on ap...,268,...,0,NaN,0,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None,None
4,1513663,2018-01-01,Aircraft Equipment Problem Less Severe; Deviat...,RCTP.Airport,B747-400,Pilot Flying; Captain,NaN,Our aircraft had just finished a 'heavy' maint...,B747-400 Captain reported a loss of hydraulic ...,190,...,0,NaN,0,exact_anomaly_code_same_location_12mo,RCTP,Airport,"Taiwan, Province of China",None,Taoyuan,large_airport
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33718,2192919,2024-12-01,Aircraft Equipment Problem Critical; Deviation...,ZZZ.Airport,Skyhawk 172/Cutlass 172,Instructor,Climb,This occurred shortly after departing from ZZZ...,C172 Flight Instructor reported cockpit smoke ...,258,...,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None,None
33719,2192908,2024-12-01,Deviation - Altitude Overshoot; Deviation / Di...,CRQ.Airport,Any Unknown or Unlisted Aircraft Manufacturer,Single Pilot; Pilot Flying,Final Approach,I departed from ZZZ with a filed IFR flight pl...,GA pilot reported they descended below the Min...,579,...,0,NaN,1,exact_anomaly_code_same_location_12mo,CRQ,Airport,Brazil,None,Caravelas,medium_airport
33720,2192884,2024-12-01,Conflict NMAC; Deviation / Discrepancy - Proce...,ZZZ.Airport,Skyhawk 172/Cutlass 172,Instructor,Final Approach,Practice approach RNAV XX into ZZZ. I am the C...,C172 flight instructor reported a near mid-air...,63,...,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None,None
33721,2192873,2024-12-01,Deviation / Discrepancy - Procedural Published...,ZZZ.Airport,A319,Ramp,Taxi,My shift started at XA:00 AM and I was assigne...,Tow team lead reported after parking aircraft ...,1930,...,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport,None,None,None,None
33722,2253308,2024-12-01,Conflict NMAC,HII.Airport,Light Transport; Low Wing; 2 Turboprop Eng,NaN,NaN,Aircraft X and Aircraft Y nearly collide over ...,Reporter reported a near mid air collision bet...,30,...,0,NaN,1,exact_anomaly_code_same_location_12mo,HII,Airport,United States,AZ,Lake Havasu City,medium_airport

In [17]:
# df.to_csv('Intermediate Input Files/LocationID.csv', index=False)

### 3.2 Consolidate Airport and Organization_Unit Values

In [18]:
df = pd.read_csv('Intermediate Input Files/LocationID.csv')

In [19]:
airport_value_counts = pd.DataFrame(df['airport'].value_counts().reset_index())

with pd.option_context('display.max_rows', None):
    display(airport_value_counts)

     airport  count
0        ZZZ  22574
1        DEN    273
2        ORD    248
3        EWR    232
4        LAX    194
5        SFO    176
6        SCT    170
7        CLT    160
8        IAH    143
9        DFW    141
10       LGA    135
11       MIA    118
12       DCA    117
13       ATL    114
14       D01    114
15       ZAB    113
16       ZDV    102
17       PHL    100
18       ZJX     98
19       NCT     97
20       ZDC     94
21       SEA     93
22       ZLC     90
23       PHX     90
24       N90     89
25       BOS     89
26       LAS     88
27       ZLA     87
28       JFK     84
29       PCT     75
30       ZMA     72
31       ZOA     71
32       ZSE     67
33       ROA     66
34       ZNY     64
35       SJC     64
36       SAN     60
37       MDW     59
38       IAD     58
39       SNA     58
40       ZAU     58
41       ZOB     57
42       MCO     57
43       ZBW     57
44       BNA     57
45       SAT     55
46       BOI     55
47       ZHU     54
48       BWI     53
49       ZTL     50
50       C90     49
51       TEB     49
52       ZFW     48
53       I90     47
54       DTW     47
55       SLC     45
56       VNY     45
57       ZMP     45
58       BUR     44
59       S46     44
60       ABQ     43
61       MEM     43
62       RNO     43
63       ASE     42
64       P50     42
65       ZKC     42
66       OAK     42
67       ZID     42
68       FLL     38
69       TPA     38
70       ELP     36
71       ZME     36
72       MSP     36
73       D10     36
74       BFI     35
75       AUS     35
76       HCF     34
77       DAL     34
78       PDX     34
79       HOU     34
80       SDF     33
81       IND     32
82       S56     32
83       HNL     32
84       A90     32
85       PIT     32
86       BJC     32
87       L30     31
88       CVG     30
89       ONT     30
90      MMFR     28
91       A80     28
92       BHM     26
93       AVL     25
94       EUG     25
95       HPN     25
96       ZAN     25
97       PBI     25
98       STL     24
99       A11     24
100     HECC     24
101      GEG     23
102      LGB     23
103      PAO     23
104      CLE     23
105      ANC     23
106      F11     23
107      RSW     22
108      APA     22
109      RDU     22
110      TUS     22
111      MYF     21
112      MRY     21
113      SBA     21
114      PDK     21
115      CMH     21
116      SYR     21
117      SQL     20
118      COS     20
119      FAI     20
120      MCI     20
121      MSY     20
122      FXE     19
123      SMF     19
124      AUO     19
125     KZAK     19
126     MMMX     18
127     LTAA     18
128      JAX     18
129      IWA     18
130      RIC     17
131      MKE     17
132      CHO     17
133      UNV     17
134      PAE     16
135      SMO     16
136      MFR     16
137      PWM     16
138      ORF     16
139      DAB     16
140      AFW     16
141      SDL     15
142      ORL     15
143      MDT     15
144      GSO     15
145      PSP     15
146      SAV     15
147      CAE     14
148      BED     14
149      SRQ     14
150      ALB     14
151      JYO     14
152      OGG     14
153      OKC     14
154     LLLL     14
155      CHS     14
156      BUF     14
157      SBN     14
158      LMO     14
159      P80     14
160      FNL     13
161     CZQX     13
162     MMUN     13
163      MMU     13
164     LLBG     13
165      DSM     13
166      CHA     13
167      BGR     13
168      CRW     13
169      PVD     13
170      D21     13
171      MSO     13
172     LFPG     12
173      LAL     12
174     VHHH     12
175      TYS     12
176      LVK     12
177      FCM     12
178     CYYZ     12
179      HTS     11
180      VNC     11
181      SGU     11
182      CAK     11
183     EGGX     11
184      OSH     11
185      MSN     11
186      F70     11
187     EGLL     11
188      SUS     11
189      DWH     11
190      GSP     11
191      BZN     11
192      MYR     11
193      JAC     11
194      BTV     11
195      GRR     11
196      DVT     11
197      EGE     11
198      OMA     10
199      AVQ     10
200      AVP     10
201      CNO     10
202      HWD     10
203      ROC     10
204      RFD     10
205      RDM     10
206     SKBO     10
207      LIT     10
208      M98     10
209     RKSI      9
210     MGGT      9
211     MKJS      9
212      HIO      9
213     RJJJ      9
214      CID      9
215     LCCC      9
216      ISP      9
217      ICT      9
218      SBP      9
219      FFZ      9
220     SBGR      9
221      GIF      9
222      BDL      9
223     MMGL      9
224      CGZ      9
225     PTKK      9
226     MYNN      9
227     RKRR      9
228      ISM      9
229      MHT      8
230      FRG      8
231      CPT      8
232      RNT      8
233      ILM      8
234      GYR      8
235      ADS      8
236      BFL      8
237      GTF      8
238      MLB      8
239      PRC      8
240      HEF      8
241      OPF      8
242      GFK      8
243      FAT      8
244      MOB      8
245      HND      8
246      STS      8
247      FDK      8
248      PWT      7
249      RNM      7
250      TRI      7
251      CRG      7
252      APC      7
253      DED      7
254      FTW      7
255      DAY      7
256      TVC      7
257      CMA      7
258      DPA      7
259      RHV      7
260      JNU      7
261      TUL      7
262      BTR      7
263     ZSHA      7
264      JWN      7
265      AMA      7
266      FPR      7
267      CHD      7
268     MROC      7
269      GJT      7
270     OPLR      7
271     MSLP      7
272      PHF      7
273      SSI      7
274      SUX      6
275      U90      6
276      SAC      6
277      TOA      6
278      R90      6
279      HDN      6
280      TRM      6
281     OEJD      6
282      MKC      6
283      TTN      6
284      LZU      6
285      X04      6
286      GAI      6
287      JAN      6
288      OMN      6
289     WSSS      6
290      CPS      6
291      PIE      6
292      P08      6
293      C83      6
294     MPTO      6
295      ITH      6
296      CKB      6
297      JVY      6
298     TJSJ      6
299      SFB      6
300      PNE      6
301      WHP      6
302      TRK      6
303      BDN      6
304      VGT      6
305      AWO      6
306      JCF      6
307     ZBPE      6
308      GMU      6
309      ITO      6
310      APF      6
311      GPT      6
312      SJU      6
313     EDDF      6
314      PGV      6
315      FSD      6
316      KTN      5
317      MGM      5
318      TTD      5
319      MWH      5
320      JNX      5
321      DXR      5
322      MRI      5
323      ELM      5
324      ACT      5
325     VIDF      5
326      POU      5
327      LRU      5
328      LAN      5
329      GRK      5
330      ABE      5
331      LNK      5
332     MMSD      5
333      CDW      5
334      LUK      5
335      BIL      5
336      BDR      5
337      SEE      5
338      ESN      5
339      BET      5
340      HII      5
341     ZSPD      5
342      BMI      5
343      CXP      5
344      BTL      5
345      ZHN      5
346      MLU      5
347      PVU      5
348      GXY      5
349      LSE      5
350      HLN      5
351      WVI      5
352      E63      5
353     CYVR      5
354     MRLB      5
355      HQZ      5
356     OJAC      5
357      FFC      5
358      MLI      5
359      TMB      5
360     PKMJ      4
361      SAF      4
362      HHR      4
363      TIX      4
364      ZWY      4
365      TLH      4
366      RDG      4
367     ZGZU      4
368      RAL      4
369      PUB      4
370     RCTP      4
371      SPI      4
372      HUF      4
373     UHMM      4
374      HYI      4
375      OGD      4
376     CZYZ      4
377     CZUL      4
378      ECP      4
379      SJT      4
380      LEX      4
381      EZF      4
382      UES      4
383     VHHK      4
384     MDSD      4
385      MAF      4
386      ZSU      4
387      MLE      4
388      LAF      4
389      U42      4
390      RVS      4
391     NFFF      4
392      FLY      4
393      PWK      4
394      MCC      4
395      OSU      4
396      BCV      4
397      SOP      4
398     RJAA      4
399      BTF      4
400      HWO      4
401      RIL      4
402      GVL      4
403     BIRD      4
404      ERI      4
405      PLU      4
406     RJTT      4
407      BIF      4
408      SUU      4
409      GUM      4
410      BGM      4
411      DYB      4
412      KOA      4
413      RAP      4
414      TSP      4
415      EVV      4
416     VVNB      4
417      CCR      4
418      RIV      4
419     MYAM      4
420      OAJ      4
421      HSV      4
422     SBCW      4
423      Y90      4
424      SMQ      4
425      TCY      4
426      CCB      4
427      SFF      4
428     UUWV      4
429     MMPR      4
430      XNA      4
431      SCK      4
432     MHLM      4
433     EIDW      4
434      FTY      4
435      ILG      4
436      COE      4
437      UAO      4
438      NEW      4
439      DET      4
440     SKED      4
441      ARR      4
442      CDC      4
443      VRB      4
444     UAAA      3
445      NUQ      3
446      LRD      3
447     ORBB      3
448      LEE      3
449      CXY      3
450      RYY      3
451      DMW      3
452      MVY      3
453     PGSN      3
454      CXO      3
455      MKT      3
456      NYL      3
457      VLD      3
458      UGN      3
459      2R2      3
460     SEFG      3
461      LOU      3
462      FLG      3
463      VPZ      3
464      PIA      3
465      JVL      3
466      CPR      3
467      FCI      3
468      REI      3
469      WRI      3
470     EDGG      3
471      BKV      3
472      46U      3
473      DIK      3
474     YSSY      3
475      GON      3
476      VPC      3
477     LHCC      3
478      EVB      3
479      MMV      3
480      ZUA      3
481      SGH      3
482     TNCA      3
483     ZBAA      3
484      SSF      3
485      FOK      3
486      HRL      3
487      ASD      3
488      LIH      3
489      VUO      3
490      UUU      3
491      LCH      3
492     MBPV      3
493     PAMR      3
494      VBT      3
495      BOW      3
496      GEU      3
497     LRBB      3
498      VIS      3
499      DIA      3
500     CYUL      3
501      VKX      3
502     MHRO      3
503      FAY      3
504      MTJ      3
505      NTD      3
506     7FL6      3
507      LBB      3
508      MQY      3
509      LVJ      3
510      BLM      3
511      N40      3
512      HXD      3
513      SBD      3
514     OJAI      3
515      LXT      3
516      47N      3
517      IKV      3
518     MUHA      3
519     SPIM      3
520     TJZS      3
521      S43      3
522      SPG      3
523      HDC      3
524      VPS      3
525      DLH      3
526      MHK      3
527      T75      3
528      LOT      3
529      3J1      3
530      OWD      3
531      TPF      3
532      AGC      3
533      S50      3
534      L18      3
535      BDU      3
536      MEV      3
537     LPPT      3
538      DRO      3
539      LYH      3
540     LTBB      3
541     MUFH      3
542     EISN      3
543      AZO      3
544      ALW      3
545      BFF      3
546      BLI      3
547      BAZ      3
548      GRB      3
549      CRP      3
550     OOMM      3
551      E10      3
552      JZP      3
553      CRQ      3
554     ZGSZ      3
555      GPI      3
556      SHV      3
557      AGS      3
558      BXK      3
559     EGTT      3
560      IWS      3
561     VABB      3
562     MHTG      3
563      RST      3
564     TKPK      3
565      CLL      3
566      TVY      2
567     EGPX      2
568      FSM      2
569      EKM      2
570      F45      2
571      MTN      2
572     EDUU      2
573      GYH      2
574      DKX      2
575      FFT      2
576      06A      2
577      GZH      2
578     SBGL      2
579      PCW      2
580      JBR      2
581      HCR      2
582      PUW      2
583      MDH      2
584      0W3      2
585      MHR      2
586      SFM      2
587      ASH      2
588     CYEG      2
589      PVC      2
590      BRD      2
591      SBM      2
592      BVY      2
593      BWG      2
594      PNS      2
595      CFO      2
596      I19      2
597      OUN      2
598      LHD      2
599      AUN      2
600      BHB      2
601      1W1      2
602     CZQM      2
603      EMT      2
604      CSG      2
605      GGW      2
606      AEG      2
607     MMQT      2
608     MTPP      2
609      33N      2
610      GYY      2
611      LNC      2
612      4I3      2
613      VCB      2
614      BYY      2
615      JQF      2
616      JZI      2
617     VABF      2
618      ACY      2
619      JRF      2
620      CEW      2
621      EDU      2
622      IAG      2
623      BCT      2
624      FNT      2
625      FAR      2
626      SLI      2
627      S95      2
628      1K1      2
629      SWO      2
630      IOW      2
631      TWF      2
632      LUF      2
633      FWA      2
634     MMCU      2
635      PAQ      2
636      OKV      2
637      TKI      2
638      JLN      2
639      CBF      2
640      CPK      2
641      MKO      2
642      CMI      2
643      7B3      2
644      7F3      2
645     SYCJ      2
646      OBE      2
647      AND      2
648      PMV      2
649      IDA      2
650      RTS      2
651      1R8      2
652      F82      2
653     EHAA      2
654     VYYF      2
655      HMP      2
656      ACK      2
657      LHW      2
658     CYMX      2
659      3DW      2
660      TIW      2
661     LIEO      2
662      X26      2
663      O88      2
664      ADQ      2
665      MMH      2
666      EAT      2
667      PSM      2
668      AVX      2
669      O69      2
670      BRO      2
671      GLS      2
672      GTU      2
673     TJIG      2
674      NUW      2
675      FHR      2
676      PYM      2
677      ABI      2
678      AJO      2
679      O61      2
680      39N      2
681      LCI      2
682      DVL      2
683      RCZ      2
684      TVL      2
685      YKM      2
686      YIP      2
687      X59      2
688      DSV      2
689      4B6      2
690      FIN      2
691      GYI      2
692      ABR      2
693      T31      2
694      CGI      2
695      I69      2
696     OMDB      2
697      ARB      2
698      SZP      2
699     MDPC      2
700      PTK      2
701     MDPP      2
702      GFL      2
703      MIC      2
704      EYE      2
705      EQY      2
706      HWV      2
707      EDC      2
708      LOM      2
709      MWO      2
710      BIH      2
711      GA2      2
712      COI      2
713      MVN      2
714      VDF      2
715      RAC      2
716     TNCM      2
717      M54      2
718      SUN      2
719      HUM      2
720     MMLO      2
721      DLZ      2
722     LEBL      2
723      OWA      2
724     LIMM      2
725      SPS      2
726      CGF      2
727     CZEG      2
728      SMD      2
729     CYYC      2
730      CVB      2
731      ILN      2
732      SUZ      2
733      AAO      2
734      OKK      2
735      PMP      2
736      SUA      2
737      BAF      2
738      7S3      2
739      LBE      2
740      TCL      2
741      VQQ      2
742      GPM      2
743      LNS      2
744      DKB      2
745      VCV      2
746      LUD      2
747      CWA      2
748     TIST      2
749      MFE      2
750      MOT      2
751     EDDM      2
752      MKL      2
753      HFY      2
754      FIT      2
755      PWA      2
756      DNL      2
757      MGJ      2
758      CVH      2
759      XNX      2
760      RYM      2
761     RCAA      2
762      SGF      2
763      OXR      2
764     RPHI      2
765      MKY      2
766      LWC      2
767      1F7      2
768      BVU      2
769      BKL      2
770      FCA      2
771      ORS      2
772      GNV      2
773      SPB      2
774      ELA      2
775      JPX      2
776      SLE      2
777      PUJ      2
778      HKS      2
779      LMT      2
780      VLL      2
781      ENN      2
782      RDD      2
783     RJBB      2
784      SEZ      2
785      DBQ      2
786      DIJ      2
787      TOL      2
788      GUC      2
789      CEU      2
790      BIS      2
791      PCZ      2
792      44N      2
793      MDD      2
794      BTP      2
795      CVC      1
796      MEZ      1
797      IXA      1
798      I43      1
799      DEC      1
800      IXD      1
801      60R      1
802      OBI      1
803      ONZ      1
804      GPH      1
805      HYA      1
806      ALM      1
807      ISO      1
808      IPT      1
809      80G      1
810      MTW      1
811      CWC      1
812     UUWW      1
813      8W2      1
814      WLD      1
815      AWG      1
816      OZW      1
817      MKG      1
818      EAU      1
819      HSD      1
820      TDF      1
821      LIC      1
822     MYEF      1
823     LECM      1
824      TPL      1
825      INF      1
826      LGC      1
827      CLW      1
828      GKY      1
829      CVS      1
830      W13      1
831     LBSR      1
832      CVN      1
833      MSV      1
834      IRK      1
835      M91      1
836      ANI      1
837      AXH      1
838      83D      1
839      PVB      1
840      NGU      1
841      7G8      1
842      OAR      1
843      PIH      1
844      W35      1
845      MRC      1
846      PVW      1
847      EEO      1
848      X60      1
849      VER      1
850      JHW      1
851      PJY      1
852      OCH      1
853      LDJ      1
854      U10      1
855      FWN      1
856      SFZ      1
857     LFPB      1
858      LWA      1
859      RBV      1
860      ODO      1
861      CCO      1
862      T35      1
863      LRO      1
864      PVR      1
865     LOWW      1
866      CYS      1
867      CDN      1
868      MTO      1
869      50R      1
870      ANP      1
871      SSQ      1
872      MWC      1
873      7S1      1
874      WYS      1
875     BIKF      1
876      THA      1
877      4M3      1
878      ORK      1
879     LCLK      1
880      RNH      1
881      EUL      1
882      COU      1
883      CGS      1
884      1N7      1
885      T67      1
886      DTS      1
887      PKB      1
888     PHLI      1
889      AUH      1
890      ATW      1
891      L35      1
892      3AU      1
893      STP      1
894      AMG      1
895     20GA      1
896     MUSC      1
897     MKJK      1
898     MWCR      1
899     MMSP      1
900      SWF      1
901     NZZO      1
902     CZVR      1
903      LNY      1
904      HUA      1
905      UNU      1
906      FUL      1
907     OMDW      1
908      PXR      1
909      3B3      1
910      ADF      1
911      MEB      1
912     15MO      1
913      GVQ      1
914     FA44      1
915      GVT      1
916      06C      1
917      SNH      1
918      TYQ      1
919      RWI      1
920      FHU      1
921      W29      1
922      F51      1
923      BVS      1
924      M03      1
925      SAA      1
926     VVTS      1
927      AJZ      1
928      MOD      1
929      BCB      1
930      AWM      1
931      SMN      1
932      JSD      1
933      S36      1
934    GUTER      1
935      PSC      1
936     EDDK      1
937     SAEF      1
938      P19      1
939      TGI      1
940      EYW      1
941      PRX      1
942      SEF      1
943      FVX      1
944     18AZ      1
945      LNN      1
946      HLX      1
947      Y23      1
948      HJH      1
949      RYN      1
950      OXC      1
951     SVZM      1
952      HDF      1
953      MYL      1
954      HLM      1
955     WI14      1
956      UIM      1
957      C02      1
958      GAF      1
959      OQU      1
960      DNN      1
961      MIO      1
962      SGJ      1
963      F05      1
964      M38      1
965      IUA      1
966      ONL      1
967      SIF      1
968     ZSWX      1
969      AFO      1
970     RPLC      1
971      TTA      1
972      TEX      1
973     MYGF      1
974      LXV      1
975     PHKO      1
976      MGY      1
977      FYJ      1
978     9PA8      1
979      2V6      1
980     CO15      1
981      SUT      1
982     MMMZ      1
983      RBG      1
984      LAW      1
985      1G3      1
986      3B1      1
987      CIU      1
988      ICL      1
989      SET      1
990      A39      1
991      UIN      1
992      POF      1
993      IYK      1
994      X52      1
995      ZZV      1
996      C44      1
997      46N      1
998      NFW      1

In [20]:
print(len(airport_value_counts))

1448

In [21]:
# Filtering to keep all those airports that appear at least 30 times in order to follow sampling size rule of thumb
discard_airports = airport_value_counts[90:]['airport']
discard_airports

90      MMFR
91       A80
92       BHM
93       AVL
94       EUG
        ...
1443     FHB
1444     2G8
1445     JCA
1446     VCT
1447     X35
Name: airport, Length: 1358, dtype: object

In [22]:
# Filtering
df['airport'] = df['airport'].where(~df['airport'].isin(discard_airports), 'other')

# Viewing
with pd.option_context('display.max_rows', None):
    display(df['airport'].value_counts())

airport
ZZZ      22574
other     4689
DEN        273
ORD        248
EWR        232
LAX        194
SFO        176
SCT        170
CLT        160
IAH        143
DFW        141
LGA        135
MIA        118
DCA        117
D01        114
ATL        114
ZAB        113
ZDV        102
PHL        100
ZJX         98
NCT         97
ZDC         94
SEA         93
PHX         90
ZLC         90
BOS         89
N90         89
LAS         88
ZLA         87
JFK         84
PCT         75
ZMA         72
ZOA         71
ZSE         67
ROA         66
SJC         64
ZNY         64
SAN         60
MDW         59
IAD         58
SNA         58
ZAU         58
MCO         57
ZBW         57
BNA         57
ZOB         57
SAT         55
BOI         55
ZHU         54
BWI         53
ZTL         50
C90         49
TEB         49
ZFW         48
I90         47
DTW         47
SLC         45
VNY         45
ZMP         45
S46         44
BUR         44
MEM         43
ABQ         43
RNO         43
ZKC         42
P50         42
ASE         42
OAK         42
ZID         42
FLL         38
TPA         38
ZME         36
D10         36
ELP         36
MSP         36
BFI         35
AUS         35
DAL         34
PDX         34
HOU         34
HCF         34
SDF         33
PIT         32
HNL         32
A90         32
IND         32
BJC         32
S56         32
L30         31
CVG         30
ONT         30
Name: count, dtype: int64

In [23]:
with pd.option_context('display.max_rows', None):
    display(df['organizational_unit'].value_counts())

organizational_unit
Airport                 22975
ARTCC                    5022
TRACON                   3778
Tower                    1883
VORTAC                     20
VOR                        12
NDB                         3
FSS                         1
TACAN                       1
Airport; AKR.Airport        1
Name: count, dtype: int64

In [24]:
# Consolidating VOR and VORTAC

df['organizational_unit'] = df['organizational_unit'].replace(
    {'VORTAC': 'VOR/VORTAC', 'VOR': 'VOR/VORTAC'}
)

# Treating other Rare Values

df['organizational_unit'] = df['organizational_unit'].replace(
    {'NDB': 'other', 'FSS': 'other', 'TACAN':'other', 'Airport; AKR.Airport': 'other'}
)

with pd.option_context('display.max_rows', None):
    display(df['organizational_unit'].value_counts())

organizational_unit
Airport       22975
ARTCC          5022
TRACON         3778
Tower          1883
VOR/VORTAC       32
other             6
Name: count, dtype: int64

### 3.3. Encode Data

In [25]:

# Dummy code airport
airport_dummies = pd.get_dummies(df['airport'], prefix = 'airport').astype(int)
df = pd.concat([df, airport_dummies], axis = 1)

# Dummy code organizational_unit
org_dummies = pd.get_dummies(df['organizational_unit'], prefix = 'org').astype(int)
df = pd.concat([df, org_dummies], axis = 1)

# One-hot encode state and airport_type
state_dummies = pd.get_dummies(df['state'], prefix='state').astype(int)
airport_type_dummies = pd.get_dummies(df['airport_type'], prefix='airport_type').astype(int)

# Insert state dummies after state column
state_idx = df.columns.get_loc('state') + 1
for col in reversed(state_dummies.columns):
    df.insert(state_idx, col, state_dummies[col])

# Insert airport_type dummies after airport_type column
airport_type_idx = df.columns.get_loc('airport_type') + 1
for col in reversed(airport_type_dummies.columns):
    df.insert(airport_type_idx, col, airport_type_dummies[col])

In [26]:
with pd.option_context('display.max_columns', None):
    display(df)

,acn,event_date,anomaly_code,location_id,aircraft_type,reporter_function,flight_phase,narrative_text,synopsis,word_count,hedge_score,passive_voice_ratio,causal_connective_count,specificity_score,named_entity_count,type_token_ratio,recurrence_flag,days_to_recurrence,is_right_censored,label_method,airport,organizational_unit,country,state,state_AK,state_AL,state_AR,state_AZ,state_CA,state_CO,state_CT,state_DC,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MA,state_MD,state_ME,state_MI,state_MN,state_MO,state_MS,state_MT,state_NC,state_ND,state_NE,state_NH,state_NJ,state_NM,state_NV,state_NY,state_OH,state_OK,state_OR,state_PA,state_RI,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY,city,airport_type,airport_type_heliport,airport_type_large_airport,airport_type_medium_airport,airport_type_seaplane_base,airport_type_small_airport,airport_A90,airport_ABQ,airport_ASE,airport_ATL,airport_AUS,airport_BFI,airport_BJC,airport_BNA,airport_BOI,airport_BOS,airport_BUR,airport_BWI,airport_C90,airport_CLT,airport_CVG,airport_D01,airport_D10,airport_DAL,airport_DCA,airport_DEN,airport_DFW,airport_DTW,airport_ELP,airport_EWR,airport_FLL,airport_HCF,airport_HNL,airport_HOU,airport_I90,airport_IAD,airport_IAH,airport_IND,airport_JFK,airport_L30,airport_LAS,airport_LAX,airport_LGA,airport_MCO,airport_MDW,airport_MEM,airport_MIA,airport_MSP,airport_N90,airport_NCT,airport_OAK,airport_ONT,airport_ORD,airport_P50,airport_PCT,airport_PDX,airport_PHL,airport_PHX,airport_PIT,airport_RNO,airport_ROA,airport_S46,airport_S56,airport_SAN,airport_SAT,airport_SCT,airport_SDF,airport_SEA,airport_SFO,airport_SJC,airport_SLC,airport_SNA,airport_TEB,airport_TPA,airport_VNY,airport_ZAB,airport_ZAU,airport_ZBW,airport_ZDC,airport_ZDV,airport_ZFW,airport_ZHU,airport_ZID,airport_ZJX,airport_ZKC,airport_ZLA,airport_ZLC,airport_ZMA,airport_ZME,airport_ZMP,airport_ZNY,airport_ZOA,airport_ZOB,airport_ZSE,airport_ZTL,airport_ZZZ,airport_other,org_ARTCC,org_Airport,org_TRACON,org_Tower,org_VOR/VORTAC,org_other
0,1507557,2018-01-01,ATC Issue All Types; Deviation / Discrepancy -...,C90.TRACON,A330,Approach,Landing,Aircraft X was assigned a runway approximately...,MLI Approach Controller reported ATC denied th...,143,0.000000,0.5556,2,0.00,7,0.5833,1,181.0,0,exact_anomaly_code_same_location_12mo,C90,TRACON,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,1513720,2018-01-01,Aircraft Equipment Problem Less Severe,ZZZ.Airport,EMB ERJ 170/175 ER/LR,Captain; Pilot Not Flying,Cruise,Pack 2 was MELed. My FO (First Officer) and I ...,ERJ-175 Captain reported diverting after exper...,318,0.003145,0.2105,3,0.75,19,0.4969,0,NaN,0,exact_anomaly_code_same_location_12mo,ZZZ,Airport,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
2,1513718,2018-01-01,Flight Deck / Cabin / Aircraft Event Illness /...,ZZZ.ARTCC,A321,Pilot Not Flying,Cruise,[A passenger] was reported as being ill and un...,A321 flight crew member reported difficulty re...,166,0.000000,0.1111,0,0.00,13,0.5689,1,120.0,0,exact_anomaly_code_same_location_12mo,ZZZ,ARTCC,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0
3,1513706,2018-01-01,Aircraft Equipment Problem Critical,ZZZ.Airport,Citation V/Ultra/Encore (C560),First Officer; Pilot Flying,Final Approach,While on approach at 1;500ft; we asked the tow...,CE-560 First Officer reported that while on ap...,268,0.000000,0.0556,1,0.50,11,0.5221,0,NaN,0,exact_anomaly_code_same_location_12mo,ZZZ,Airport,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
4,1513663,2018-01-01,Aircraft Equipment Problem Less Severe; Deviat...,RCTP.Airport,B747-400,Pilot Flying; Captain,NaN,Our aircraft had just finished a 'heavy' maint...,B747-400 Captain reported a loss of hydraulic ...,190,0.000000,0.0667,0,0.25,5,0.5812,0,NaN,0,exact_anomaly_code_same_location_12mo,other,Airport,"Taiwan, Province of China",NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Taoyuan,large_airport,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33718,2192919,2024-12-01,Aircraft Equipment Problem Critical; Deviation...,ZZZ.Airport,Skyhawk 172/Cutlass 172,Instructor,Climb,This occurred shortly after departing from ZZZ...,C172 Flight Instructor reported cockpit smoke ...,258,0.000000,0.2308,0,0.25,19,0.6151,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
33719,2192908,2024-12-01,Deviation - Altitude Overshoot; Deviation / Di...,CRQ.Airport,Any Unknown or Unlisted Aircraft Manufacturer,Single Pilot; Pilot Flying,Final Approach,I departed from ZZZ with a filed IFR flight pl...,GA pilot reported they descended below the Min...,579,0.001727,0.2800,4,0.50,33,0.4220,0,NaN,1,exact_anomaly_code_same_location_12mo,other,Airport,Brazil,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Caravelas,medium_airport,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0
33720,2192884,2024-12-01,Conflict NMAC; Deviation / Discrepancy - Proce...,ZZZ.Airport,Skyhawk 172/Cutlass 172,Instructor,Final Approach,Practice approach RNAV XX into ZZZ. I am the C...,C172 flight instructor reported a near mid-air...,63,0.000000,0.0000,0,0.25,8,0.7969,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
33721,2192873,2024-12-01,Deviation / Discrepancy - Procedural Published...,ZZZ.Airport,A319,Ramp,Taxi,My shift started at XA:00 AM and I was assigne...,Tow team lead reported after parking aircraft ...,1930,0.005181,0.3210,5,0.75,49,0.2664,0,NaN,1,exact_anomaly_code_same_location_12mo,ZZZ,Airport,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
33722,2253308,2024-12-01,Conflict NMAC,HII.Airport,Light Transport; Low Wing; 2 Turboprop Eng,NaN,NaN,Aircraft X and Aircraft Y nearly collide over ...,Reporter reported a near mid air collision bet...,30,0.000000,0.0000,0,0.00,3,0.9355,0,NaN,1,exact_anomaly_code_same_location_12mo,other,Airport,United States,AZ,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Lake Havasu City,medium_airport,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0

In [27]:
len(df[(df['airport']=='ZZZ') & (df['recurrence_flag'] == 1)])

7749

## 4. Export Data

In [28]:
# Define and drop extraneous variables
to_drop = ['event_date', 'anomaly_code', 'aircraft_type', 'reporter_function', 'flight_phase', 'narrative_text', 'synopsis', 'word_count', 'hedge_score', 'passive_voice_ratio', 'causal_connective_count', 'specificity_score', 'named_entity_count', 'type_token_ratio', 'recurrence_flag', 'days_to_recurrence', 'is_right_censored', 'label_method']
df = df.drop(to_drop, axis=1)

In [29]:
# Export
# df.to_csv('Output/Data 2 - location_id clean.csv', index=False)